#!/bin/bash
set -e

chown -R mysql:mysql /var/lib/mysql

# if the MYSQL dir hasn't been initialized, do so
if [[ ! -d "/var/lib/mysql/mysql" ]]; then
    echo "** MySQL install"
    mysql_install_db --user mysql > /dev/null

    MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-""}
    MYSQL_DATABASE=${MYSQL_DATABASE:-""}
    MYSQL_USER=${MYSQL_USER:-""}
    MYSQL_PASSWORD=${MYSQL_PASSWORD:-""}
    MYSQLD_ARGS=${MYSQLD_ARGS:-""}

    tfile=`mktemp`
    if [[ ! -f "$tfile" ]]; then
        return 1
    fi

    cat << EOF > $tfile
USE mysql;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY "$MYSQL_ROOT_PASSWORD" WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

    if [[ $MYSQL_DATABASE != "" ]]; then
        echo "CREATE DATABASE IF NOT EXISTS \`$MYSQL_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;" >> $tfile

        if [[ $MYSQL_USER != "" ]]; then
            echo "GRANT ALL ON \`$MYSQL_DATABASE\`.* to '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';" >> $tfile
    	echo "FLUSH PRIVILEGES;" >> $tfile
        fi
    fi

    echo "** MySQLd bootstrap"
    /usr/sbin/mysqld --bootstrap --verbose=0 $MYSQLD_ARGS < $tfile
    rm -f $tfile
fi

echo "** MySQLd $MYSQLD_ARGS"
exec /usr/sbin/mysqld $MYSQLD_ARGS
